function tests = testFeatureParity
%TESTFEATUREPARITY  Prove the MATLAB feature builder matches the Python one exactly.
%
%   runtests('matlab/tests/testFeatureParity')
%
%   The model is TRAINED by ml/python/meteor/features.py and RUN by
%   sih.prediction.buildFeatureFrame. If the two builders disagree, the network is fed
%   different numbers at inference than it saw in training. Nothing throws. Accuracy quietly
%   collapses and it looks like a planner fault. AGENTS.md section 5 makes this a hard
%   requirement, and this file is the only thing that enforces it.
%
%   The fixture is generated by ml/python/tests/test_parity.py. Regenerate it whenever
%   features.py changes and commit the two together - a fixture older than features.py
%   proves nothing.
tests = functiontests(localfunctions);
end


function setupOnce(tc)
here = fileparts(mfilename('fullpath'));
root = fileparts(fileparts(here));                       % <repo>/matlab/tests -> <repo>
addpath(fullfile(root, 'matlab'));
f = fullfile(root, 'ml', 'python', 'tests', 'parity_fixture.json');
tc.assertTrue(isfile(f), sprintf( ...
    ['parity_fixture.json is missing. Generate it first:\n' ...
     '    python3 ml/python/tests/test_parity.py\n' ...
     'Looked in: %s'], f));
tc.TestData.fx = jsondecode(fileread(f));
end


function testEveryCaseMatchesPython(tc)
fx  = tc.TestData.fx;
tol = fx.tolerance;
cases = fx.cases;
if ~iscell(cases)
    cases = num2cell(cases);
end

for k = 1:numel(cases)
    c = cases{k};
    name = c.name;

    boxes = iBoxes(c.boxes);
    prev  = iBoxes(c.prev);
    ego   = struct('Speed', c.ego.speed, 'YawRate', c.ego.yaw_rate, ...
                   'Accel', c.ego.accel, 'CandAction', c.ego.cand_action);

    frame = sih.prediction.buildFeatureFrame(boxes, prev, ego, c.img_w, c.img_h);

    want = iExpected(c.expected_data);
    got  = double(frame.Data);

    tc.verifyEqual(size(got), size(want), sprintf( ...
        'case "%s": Data is %s, Python produced %s', name, mat2str(size(got)), mat2str(size(want))));

    if isempty(want)
        continue
    end

    d = abs(got - want);
    [worst, idx] = max(d(:));
    [row, col] = ind2sub(size(d), idx);
    tc.verifyLessThan(worst, tol, sprintf( ...
        ['case "%s": feature %d of row %d differs by %g\n' ...
         '  MATLAB %.10g   Python %.10g\n' ...
         'Feature numbers are AGENTS.md S2 positions. 10 is tau, 11 the lateral ' ...
         'time-to-cross, 12-27 the class one-hot, 28-31 ego state.'], ...
        name, col, row, worst, got(row, col), want(row, col)));

    wantAdj = iExpected(c.expected_adj);
    tc.verifyEqual(double(frame.Adjacency), wantAdj, 'AbsTol', tol, sprintf( ...
        'case "%s": Adjacency differs. S2 says it is always emitted even though the LSTM ignores it.', name));

    tc.verifyEqual(double(frame.TrackIDs(:)), double(c.expected_ids(:)), sprintf( ...
        'case "%s": TrackIDs differ or are in a different order. S1 rule 1 fixes the order.', name));
end
end


function testEmptyListDoesNotError(tc)
% S1 guarantee 3: TrackList may be empty and consumers must not error.
ego = struct('Speed', 0, 'YawRate', 0, 'Accel', 0, 'CandAction', 0);
empty = iBoxes([]);
frame = sih.prediction.buildFeatureFrame(empty, empty, ego, 1920, 1080);
tc.verifyEmpty(frame.Data);
tc.verifyEmpty(frame.TrackIDs);
end


function testFeaturePositionsAreFrozen(tc)
% S2: positions 1-31 never move. This catches an append that shifted something.
ego = struct('Speed', 3.5, 'YawRate', 0.25, 'Accel', -1.25, 'CandAction', -1.0);
box = struct('UMin', 800, 'VMin', 500, 'UMax', 900, 'VMax', 600, ...
             'ClassID', uint8(10), 'TrackID', uint32(42), 'T', 1.0);
frame = sih.prediction.buildFeatureFrame(box, iBoxes([]), ego, 1920, 1080);
d = double(frame.Data);

tc.verifyEqual(numel(d), 31, 'S2 fixes the vector at 31 values.');
tc.verifyEqual(d(28), 3.5,  'AbsTol', 1e-6, 'feature 28 must be ego speed');
tc.verifyEqual(d(29), 0.25, 'AbsTol', 1e-6, 'feature 29 must be ego yaw rate');
tc.verifyEqual(d(30), -1.25,'AbsTol', 1e-6, 'feature 30 must be ego acceleration');
tc.verifyEqual(d(31), -1.0, 'AbsTol', 1e-6, 'feature 31 must be the candidate action (S6)');
% cow is ClassID 10 (S5), so the one-hot bit belongs at 12 + 10 = 22
tc.verifyEqual(d(22), 1.0, 'AbsTol', 1e-6, 'a cow must set feature 22, not another position');
tc.verifyEqual(sum(d(12:27)), 1.0, 'AbsTol', 1e-6, 'exactly one class bit may be set');
end


function out = iBoxes(s)
%IBOXES  jsondecode gives a struct array, a cell array or [] depending on the JSON. Normalise.
proto = struct('UMin', {}, 'VMin', {}, 'UMax', {}, 'VMax', {}, ...
               'ClassID', {}, 'TrackID', {}, 'T', {});
if isempty(s)
    out = proto;
    return
end
if iscell(s)
    s = [s{:}];
end
out = repmat(struct('UMin', 0, 'VMin', 0, 'UMax', 0, 'VMax', 0, ...
                    'ClassID', uint8(0), 'TrackID', uint32(0), 'T', 0), numel(s), 1);
for i = 1:numel(s)
    out(i).UMin = s(i).u_min;
    out(i).VMin = s(i).v_min;
    out(i).UMax = s(i).u_max;
    out(i).VMax = s(i).v_max;
    % ClassID is deliberately NOT cast here: the fixture includes out-of-range and negative
    % values on purpose, and casting to uint8 would clamp them before the builder sees them.
    out(i).ClassID = s(i).class_id;
    out(i).TrackID = uint32(s(i).track_id);
    out(i).T = s(i).t;
end
end


function m = iExpected(v)
%IEXPECTED  jsondecode collapses an N-by-1 array of rows into a vector. Restore the matrix.
%
%   THE EMPTY CASE IS 0-BY-31, NOT 0-BY-0.  AGENTS.md section 3, S2: FeatureFrame
%   .Data is [N x 31 single], so an empty frame still has 31 columns. features.py
%   already returns np.zeros((0, 31)) and is correct. The fixture is what loses the
%   column count: JSON serialises an empty array as [] and jsondecode gives back
%   0-by-0, so this helper was comparing 0-by-31 against 0-by-0 and failing a frame
%   that was right on both sides. Fixed on the MATLAB side because Python matches
%   the contract and MATLAB did not.
if isempty(v)
    m = zeros(0, 31);
elseif iscell(v)
    m = cell2mat(cellfun(@(r) r(:).', v, 'UniformOutput', false));
elseif isvector(v)
    m = v(:).';
else
    m = v;
end
end
